services:

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finance-sqlserver
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - finance_network
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  # # Redis
  # redis:
  #   image: redis:alpine
  #   container_name: finance-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # # RabbitMQ
  # rabbitmq:
  #   image: rabbitmq:management
  #   container_name: finance-rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin123
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   restart: unless-stopped

  # # Seq
  # seq:
  #   image: datalust/seq:latest
  #   container_name: finance-seq
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "5341:80"
  #   volumes:
  #     - seq_data:/data
  #   restart: unless-stopped

  # API Gateway
  apigateway:
    build:
      context: ../           # 👈 Set context to one level above to include src and .sln
      dockerfile: src/ApiGateway/PersonalFinance.ApiGateway/Dockerfile
    container_name: finance-apigateway
    ports:
      - "5000:5000"
    networks:
      - finance_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
  
  # User Management
  user-management:
    build:
      context: ../           # 👈 Set context to one level above to include src and .sln
      dockerfile: src/Services/PersonalFinance.Services.UserManagement/Dockerfile
    container_name: finance-usermanagement
    ports:
      - "5100:5100"
    networks:
      - finance_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

volumes:
  sqlserver_data:
  redis_data:
  rabbitmq_data:
  seq_data:

networks:
  finance_network:
    driver: bridge